const router = require('express').Router();
const { requireAuth, requireRole } = require('../middleware/auth');
const Rental = require('../models/Rental');
const Equipment = require('../models/Equipment');
const Site = require('../models/Site');
const User = require('../models/User');
const { raiseAlert } = require('../services/alertEngine');
const { sendNotification } = require('../services/emailService');
const PDFDocument = require('pdfkit');

const TN = { latMin: 8.0, latMax: 13.5, lngMin: 76.0, lngMax: 80.5 };
const inTN = (lat, lng) => lat >= TN.latMin && lat <= TN.latMax && lng >= TN.lngMin && lng <= TN.lngMax;

const round2 = (v) => (typeof v === 'number' ? Math.round(v * 100) / 100 : v);

// POST /api/rentals/site-request
router.post('/site-request', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const { siteName, lat, lng, equipmentTypeNeeded, notes } = req.body;
    if (!siteName || lat == null || lng == null)
      return res.status(400).json({ message: 'siteName, lat and lng are required' });
    const la = parseFloat(lat), lo = parseFloat(lng);
    if (!inTN(la, lo))
      return res.status(400).json({
        message: `Coordinates must be within Tamil Nadu (lat 8.0–13.5, lng 76.0–80.5). Got: ${la}, ${lo}`,
      });
    const site = await Site.create({
      name: siteName,
      location: { lat: la, lng: lo },
      status: 'pending',
      submittedBy: req.user.id,
      equipmentTypeNeeded: equipmentTypeNeeded || '',
      notes: notes || '',
    });
    res.status(201).json(site);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/my-site-requests
router.get('/my-site-requests', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const sites = await Site.find({ submittedBy: req.user.id }).sort({ createdAt: -1 });
    res.json(sites);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/mine
router.get('/mine', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const rentals = await Rental.find({ customerId: req.user.id }).populate({ path: 'equipmentId', populate: { path: 'siteId' } });
    const now = new Date();

    for (const rental of rentals) {
      if (rental.status === 'ongoing' && rental.checkOutDate < now) {
        rental.status = 'overdue';
        await rental.save();

        raiseAlert(
          rental.equipmentId._id,
          'overdue',
          `Rental for equipment ${rental.equipmentId.equipmentId} is overdue`,
          'high'
        ).catch(err => console.error('raiseAlert error:', err.message));

        // Email notification — never throws
        const customer = await User.findById(req.user.id, 'email name').lean();
        if (customer?.email) {
          sendNotification(
            customer.email,
            `CAT Rental — Equipment ${rental.equipmentId.equipmentId} Overdue`,
            `Hi ${customer.name},\n\nYour rental for ${rental.equipmentId.type} (${rental.equipmentId.equipmentId}) was due on ${new Date(rental.checkOutDate).toLocaleDateString()} and is now overdue.\n\nPlease return the equipment as soon as possible.\n\n— CAT Rental Team`
          );
        }
      }
    }

    res.json(rentals);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/export-pdf & /api/reports/pdf — PDF Report Generator for Manager & Admin Fleet Summary
const generateFleetPDF = async (req, res) => {
  try {
    let eqFilter = {};
    if (req.user.role === 'manager') {
      eqFilter.siteId = { $in: req.user.assignedSites || [] };
    }
    const equipments = await Equipment.find(eqFilter).populate('siteId', 'name').populate('lastOperatorId', 'name').lean();
    
    let rentalFilter = {};
    if (req.user.role === 'manager') {
      rentalFilter.equipmentId = { $in: equipments.map(e => e._id) };
    }
    const rentals = await Rental.find(rentalFilter).populate('equipmentId', 'equipmentId type').populate('customerId', 'name email').sort({ checkInDate: -1 }).limit(20).lean();
    const currentUser = await User.findById(req.user.id, 'name email role').lean();

    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="CAT-Rental-Fleet-Report-${Date.now()}.pdf"`);
    doc.pipe(res);

    // Header Banner
    doc.rect(40, 40, 515, 50).fill('#18181b');
    doc.fillColor('#FFC500').fontSize(20).font('Helvetica-Bold').text('CAT RENTALS', 55, 52);
    doc.fillColor('#ffffff').fontSize(12).font('Helvetica').text('SMART EQUIPMENT & TELEMATICS FLEET REPORT', 200, 56);

    doc.fillColor('#000000').moveDown(2);

    // Metadata Bar
    doc.fontSize(9).font('Helvetica-Bold').text(`Generated By: `, { continued: true })
       .font('Helvetica').text(`${currentUser?.name || 'User'} (${currentUser?.role?.toUpperCase() || 'MANAGER'})   |   Date: ${new Date().toLocaleString()}`);
    doc.moveDown(0.8);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#e4e4e7');
    doc.moveDown(0.8);

    // Summary Statistics Cards
    const totalEq = equipments.length;
    const activeEq = equipments.filter(e => e.status === 'active').length;
    const idleEq = equipments.filter(e => e.status === 'idle').length;
    const overdueEq = equipments.filter(e => e.status === 'overdue').length;

    doc.fontSize(12).font('Helvetica-Bold').text('FLEET STATUS SUMMARY');
    doc.moveDown(0.4);
    doc.fontSize(10).font('Helvetica')
       .text(`Total Assets: ${totalEq}   |   Active: ${activeEq}   |   Idle: ${idleEq}   |   Overdue: ${overdueEq}`);
    doc.moveDown(1);

    // Equipment Inventory Table
    doc.fontSize(12).font('Helvetica-Bold').text('EQUIPMENT INVENTORY & TELEMATICS');
    doc.moveDown(0.4);

    // cols: id=40(w60), type=105(w90), site=200(w130), status=335(w70), rest=410(w50), work=465(w55)
    const cols = { id: 40, type: 105, site: 200, status: 335, rest: 410, work: 465 };
    doc.fontSize(9).font('Helvetica-Bold');
    const headerY = doc.y;
    doc.text('Asset ID',       cols.id,     headerY, { width: 60,  continued: true });
    doc.text('Category',       cols.type,   headerY, { width: 90,  continued: true });
    doc.text('Stationed Site', cols.site,   headerY, { width: 130, continued: true });
    doc.text('Status',         cols.status, headerY, { width: 70,  continued: true });
    doc.text('Rest (h)',       cols.rest,   headerY, { width: 50,  continued: true });
    doc.text('Max (h)',        cols.work,   headerY, { width: 55 });
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#18181b');
    doc.moveDown(0.4);

    doc.font('Helvetica').fontSize(8);
    equipments.forEach((eq) => {
      if (doc.y > 740) doc.addPage();
      const y = doc.y;
      doc.text((eq.equipmentId || 'N/A').substring(0, 9),              cols.id,     y, { width: 60 });
      doc.text((eq.type || 'N/A').substring(0, 12),                    cols.type,   y, { width: 90 });
      doc.text((eq.siteId?.name || 'Unassigned').substring(0, 18),     cols.site,   y, { width: 130 });
      doc.text((eq.status || 'N/A').toUpperCase().substring(0, 10),    cols.status, y, { width: 70 });
      doc.text(String(eq.restTimeHours ?? 8),                          cols.rest,   y, { width: 50 });
      doc.text(String(eq.maxWorkHoursPerDay ?? 10),                    cols.work,   y, { width: 55 });
      doc.moveDown(0.4);
    });

    doc.moveDown(1);
    if (doc.y > 680) doc.addPage();

    // Active Customer Rentals Section
    doc.fontSize(12).font('Helvetica-Bold').text('ACTIVE RENTAL CONTRACTS & STATUS');
    doc.moveDown(0.4);

    const rCols = { eq: 40, cust: 135, checkIn: 270, checkOut: 360, st: 450 };
    doc.fontSize(9).font('Helvetica-Bold');
    const rHeaderY = doc.y;
    doc.text('Equipment',  rCols.eq,      rHeaderY, { width: 90 });
    doc.text('Customer',   rCols.cust,    rHeaderY, { width: 130 });
    doc.text('Check-In',   rCols.checkIn, rHeaderY, { width: 85 });
    doc.text('Check-Out',  rCols.checkOut,rHeaderY, { width: 85 });
    doc.text('Status',     rCols.st,      rHeaderY, { width: 65 });
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#18181b');
    doc.moveDown(0.4);

    // Fixed column positions — widths chosen so no column overlaps with realistic data
    // rCols.eq=40 (width 90), cust=135 (width 130), checkIn=270 (width 85), checkOut=360 (width 85), st=450 (width 65)
    const fmtD = (d) => (d ? new Date(d).toLocaleDateString('en-GB') : '—');
    doc.font('Helvetica').fontSize(8);
    rentals.forEach((r) => {
      if (doc.y > 740) doc.addPage();
      const y = doc.y;
      doc.text((r.equipmentId?.equipmentId || 'N/A').substring(0, 10), rCols.eq,      y, { width: 90 });
      doc.text((r.customerId?.name || 'N/A').substring(0, 18),          rCols.cust,    y, { width: 130 });
      doc.text(fmtD(r.checkInDate),                                      rCols.checkIn, y, { width: 85 });
      doc.text(fmtD(r.checkOutDate),                                     rCols.checkOut,y, { width: 85 });
      doc.text((r.status || 'N/A').toUpperCase().substring(0, 10),       rCols.st,      y, { width: 65 });
      doc.moveDown(0.4);
    });

    if (rentals.length === 0) {
      doc.text('No active rentals found.', 40, doc.y);
    }

    doc.end();
  } catch (err) {
    console.error('PDF export error:', err);
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate PDF report', error: err.message });
    }
  }
};

router.get('/export-pdf', requireAuth, generateFleetPDF);
router.get('/mine/report', requireAuth, generateFleetPDF);

// POST /api/rentals/checkin
router.post('/checkin', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const { equipmentId } = req.body;
    const eq = await Equipment.findOne({ equipmentId });
    if (!eq) return res.status(404).json({ message: 'Equipment not found' });

    const existing = await Rental.findOne({ equipmentId: eq._id, status: { $in: ['ongoing', 'overdue'] } });
    if (existing) return res.status(400).json({ message: 'Equipment is already rented out' });

    const checkInDate = new Date();
    const checkOutDate = new Date(checkInDate.getTime() + 24 * 60 * 60 * 1000);

    const rental = await Rental.create({
      equipmentId: eq._id,
      customerId: req.user.id,
      checkInDate,
      checkOutDate,
      status: 'ongoing',
    });

    res.status(201).json(rental);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/rentals/checkout
router.post('/checkout', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const { equipmentId } = req.body;
    const eq = await Equipment.findOne({ equipmentId });
    if (!eq) return res.status(404).json({ message: 'Equipment not found' });

    const rental = await Rental.findOne({
      equipmentId: eq._id,
      customerId: req.user.id,
      status: { $in: ['ongoing', 'overdue'] },
    });
    if (!rental) return res.status(404).json({ message: 'Active rental not found for this equipment' });

    rental.status = 'returned';
    rental.actualReturnDate = new Date();
    await rental.save();

    res.json(rental);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/:id/status
router.get('/:id/status', requireAuth, async (req, res) => {
  try {
    const rental = await Rental.findById(req.params.id);
    if (!rental) return res.status(404).json({ message: 'Rental not found' });
    res.json({ status: rental.status });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
