const router = require('express').Router();
const { requireAuth, requireRole } = require('../middleware/auth');
const Rental = require('../models/Rental');
const Equipment = require('../models/Equipment');
const User = require('../models/User');
const { raiseAlert } = require('../services/alertEngine');
const { sendNotification } = require('../services/emailService');
const PDFDocument = require('pdfkit');

const round2 = (v) => (typeof v === 'number' ? Math.round(v * 100) / 100 : v);

// GET /api/rentals/mine
router.get('/mine', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const rentals = await Rental.find({ customerId: req.user.id }).populate('equipmentId');
    const now = new Date();

    for (const rental of rentals) {
      if (rental.status === 'ongoing' && rental.checkOutDate < now) {
        rental.status = 'overdue';
        await rental.save();

        raiseAlert(
          rental.equipmentId._id,
          'overdue',
          `Rental for equipment ${rental.equipmentId.equipmentId} is overdue`,
          'high'
        ).catch(err => console.error('raiseAlert error:', err.message));

        // Email notification — never throws
        const customer = await User.findById(req.user.id, 'email name').lean();
        if (customer?.email) {
          sendNotification(
            customer.email,
            `CAT Rental — Equipment ${rental.equipmentId.equipmentId} Overdue`,
            `Hi ${customer.name},\n\nYour rental for ${rental.equipmentId.type} (${rental.equipmentId.equipmentId}) was due on ${new Date(rental.checkOutDate).toLocaleDateString()} and is now overdue.\n\nPlease return the equipment as soon as possible.\n\n— CAT Rental Team`
          );
        }
      }
    }

    res.json(rentals);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/export-pdf & /api/reports/pdf — PDF Report Generator for Manager & Admin Fleet Summary
const generateFleetPDF = async (req, res) => {
  try {
    const equipments = await Equipment.find().populate('siteId', 'name').populate('lastOperatorId', 'name').lean();
    const rentals = await Rental.find().populate('equipmentId', 'equipmentId type').populate('customerId', 'name email').sort({ checkInDate: -1 }).limit(20).lean();
    const currentUser = await User.findById(req.user.id, 'name email role').lean();

    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="CAT-Rental-Fleet-Report-${Date.now()}.pdf"`);
    doc.pipe(res);

    // Header Banner
    doc.rect(40, 40, 515, 50).fill('#18181b');
    doc.fillColor('#FFC500').fontSize(20).font('Helvetica-Bold').text('CAT RENTALS', 55, 52);
    doc.fillColor('#ffffff').fontSize(12).font('Helvetica').text('SMART EQUIPMENT & TELEMATICS FLEET REPORT', 200, 56);

    doc.fillColor('#000000').moveDown(2);

    // Metadata Bar
    doc.fontSize(9).font('Helvetica-Bold').text(`Generated By: `, { continued: true })
       .font('Helvetica').text(`${currentUser?.name || 'User'} (${currentUser?.role?.toUpperCase() || 'MANAGER'})   |   Date: ${new Date().toLocaleString()}`);
    doc.moveDown(0.8);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#e4e4e7');
    doc.moveDown(0.8);

    // Summary Statistics Cards
    const totalEq = equipments.length;
    const activeEq = equipments.filter(e => e.status === 'active').length;
    const idleEq = equipments.filter(e => e.status === 'idle').length;
    const overdueEq = equipments.filter(e => e.status === 'overdue').length;

    doc.fontSize(12).font('Helvetica-Bold').text('FLEET STATUS SUMMARY');
    doc.moveDown(0.4);
    doc.fontSize(10).font('Helvetica')
       .text(`Total Assets: ${totalEq}   |   Active: ${activeEq}   |   Idle: ${idleEq}   |   Overdue: ${overdueEq}`);
    doc.moveDown(1);

    // Equipment Inventory Table
    doc.fontSize(12).font('Helvetica-Bold').text('EQUIPMENT INVENTORY & TELEMATICS');
    doc.moveDown(0.4);

    const cols = { id: 40, type: 110, site: 210, status: 350, rest: 430, work: 490 };
    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('Asset ID',       cols.id,   doc.y, { continued: true });
    doc.text('Category',       cols.type, doc.y, { continued: true });
    doc.text('Stationed Site', cols.site, doc.y, { continued: true });
    doc.text('Status',         cols.status, doc.y, { continued: true });
    doc.text('Rest (h)',       cols.rest, doc.y, { continued: true });
    doc.text('Max (h)',        cols.work, doc.y);
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#18181b');
    doc.moveDown(0.4);

    doc.font('Helvetica').fontSize(8);
    equipments.forEach((eq) => {
      if (doc.y > 740) doc.addPage();
      const y = doc.y;
      doc.text(eq.equipmentId || 'N/A',            cols.id,     y, { continued: true });
      doc.text(eq.type || 'N/A',                   cols.type,   y, { continued: true });
      doc.text(eq.siteId?.name || 'Unassigned',     cols.site,   y, { continued: true });
      doc.text((eq.status || 'N/A').toUpperCase(),  cols.status, y, { continued: true });
      doc.text(String(eq.restTimeHours ?? 8),       cols.rest,   y, { continued: true });
      doc.text(String(eq.maxWorkHoursPerDay ?? 10), cols.work,   y);
      doc.moveDown(0.4);
    });

    doc.moveDown(1);
    if (doc.y > 680) doc.addPage();

    // Active Customer Rentals Section
    doc.fontSize(12).font('Helvetica-Bold').text('ACTIVE RENTAL CONTRACTS & STATUS');
    doc.moveDown(0.4);

    const rCols = { eq: 40, cust: 140, checkIn: 280, checkOut: 400, st: 490 };
    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('Equipment',    rCols.eq,       doc.y, { continued: true });
    doc.text('Customer',     rCols.cust,     doc.y, { continued: true });
    doc.text('Check-In',     rCols.checkIn,  doc.y, { continued: true });
    doc.text('Check-Out',    rCols.checkOut, doc.y, { continued: true });
    doc.text('Status',       rCols.st,       doc.y);
    doc.moveDown(0.3);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#18181b');
    doc.moveDown(0.4);

    doc.font('Helvetica').fontSize(8);
    rentals.forEach((r) => {
      if (doc.y > 740) doc.addPage();
      const y = doc.y;
      const fmt = (d) => (d ? new Date(d).toLocaleDateString() : '—');
      doc.text(r.equipmentId?.equipmentId || 'N/A', cols.eq,       y, { continued: true });
      doc.text(r.customerId?.name || 'N/A',          rCols.cust,     y, { continued: true });
      doc.text(fmt(r.checkInDate),                  rCols.checkIn,  y, { continued: true });
      doc.text(fmt(r.checkOutDate),                 rCols.checkOut, y, { continued: true });
      doc.text((r.status || 'N/A').toUpperCase(),    rCols.st,       y);
      doc.moveDown(0.4);
    });

    if (rentals.length === 0) {
      doc.text('No active rentals found.', 40, doc.y);
    }

    doc.end();
  } catch (err) {
    console.error('PDF export error:', err);
    if (!res.headersSent) {
      res.status(500).json({ message: 'Failed to generate PDF report', error: err.message });
    }
  }
};

router.get('/export-pdf', requireAuth, generateFleetPDF);
router.get('/mine/report', requireAuth, generateFleetPDF);

// POST /api/rentals/checkin
router.post('/checkin', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const { equipmentId } = req.body;
    const eq = await Equipment.findOne({ equipmentId });
    if (!eq) return res.status(404).json({ message: 'Equipment not found' });

    const existing = await Rental.findOne({ equipmentId: eq._id, status: { $in: ['ongoing', 'overdue'] } });
    if (existing) return res.status(400).json({ message: 'Equipment is already rented out' });

    const checkInDate = new Date();
    const checkOutDate = new Date(checkInDate.getTime() + 24 * 60 * 60 * 1000);

    const rental = await Rental.create({
      equipmentId: eq._id,
      customerId: req.user.id,
      checkInDate,
      checkOutDate,
      status: 'ongoing',
    });

    res.status(201).json(rental);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST /api/rentals/checkout
router.post('/checkout', requireAuth, requireRole('customer'), async (req, res) => {
  try {
    const { equipmentId } = req.body;
    const eq = await Equipment.findOne({ equipmentId });
    if (!eq) return res.status(404).json({ message: 'Equipment not found' });

    const rental = await Rental.findOne({
      equipmentId: eq._id,
      customerId: req.user.id,
      status: { $in: ['ongoing', 'overdue'] },
    });
    if (!rental) return res.status(404).json({ message: 'Active rental not found for this equipment' });

    rental.status = 'returned';
    rental.actualReturnDate = new Date();
    await rental.save();

    res.json(rental);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET /api/rentals/:id/status
router.get('/:id/status', requireAuth, async (req, res) => {
  try {
    const rental = await Rental.findById(req.params.id);
    if (!rental) return res.status(404).json({ message: 'Rental not found' });
    res.json({ status: rental.status });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
